## Introduction to Julia by Dr. Mohammad Masiur Rahaman (masiurr@iitbbs.ac.in)

## How to print ?

Use **println()** to print

In [1]:
println("Julia")

Julia


In [2]:
println("Let us learn Julia")

Let us learn Julia


In [3]:
100
400
println("500")
600
700
800;

500


## How to assign variables?

No need to define explicitely the variable type.

All we need the variable name, value and an equal sign.

**Julia figures out the type of the variable automatically.**

In [1]:
 a = 2
 typeof(a)

Int64

In [2]:
b = 2.5 
typeof(b)

Float64

In [3]:
c = "Myself Dr. Mohammad Masiur Rahaman"
typeof(c)

String

### Re-assign a value to a variable

After assigning a value to a variable, we can reassign a value to a variable without any issue.

In [4]:
a = c
typeof(a)

String

## How to comment

In [5]:
 # a single line comment #

In [6]:
#=
For multiline comment
use #= =#
=#

## Syntax for basic math

In [7]:
sum = 3 + 5 + 6

14

In [8]:
difference = 10 - 4 

6

In [10]:
product = 5 * 6* 2

60

In [11]:
quotient = 50/10

5.0

In [12]:
power = 10^3

1000

In [13]:
modulus = 101 % 2

1

# Strings

## How to get a string ? 

Enclose your characters in **" "** or **""" """**

In [14]:
s1 = "I am a string"

"I am a string"

In [15]:
s2 = """I am also a string"""

"I am also a string"

## What is the difference between single and triple quotes used for string

one can use qutation marks in case of string using triple quotes.

In [16]:
"Here we get an "error" because of ambiguity where the quote ends"

LoadError: syntax: cannot juxtapose string literal

In [17]:
""" Look, no "error" now!"""

" Look, no \"error\" now!"

## Single quote defines a character, not a string

In [18]:
typeof('a')

Char

In [19]:
'we get an error here'

LoadError: syntax: character literal contains multiple characters

## String interpolation

We can use **$** sign to use existing variables into a string and to evaluate expressions within a string. 

In [4]:
name = "Masiur"
subject = "Julia"
number_registered = 45

45

In [5]:
println("Hello, my name is $name")

Hello, my name is Masiur


In [6]:
println("I am teaching $subject to you")

I am teaching Julia to you


In [7]:
println("No of students enrolled in this course is $number_registered")

No of students enrolled in this course is 45


## String concatenation

Three ways:
1. Use **string()** function. **string()** converts non string to a string.
2. Use * 
3. Use string interpolation through **$**

In [34]:
string("I think ",  80, " is reasonable number of students")

"I think 80 is reasonable number of students"

In [35]:
s3 = "Let us learn "
s4 = "new programming language Julia"
s3*s4

"Let us learn new programming language Julia"

In [36]:
"$s3$s4"

"Let us learn new programming language Julia"

# Data Structures

Once we work with many pieces of data at once, it will be convenient for us to store data in structures 
like arrays or dictionaries rather than just relying on variables.

Types of data structures:

1. Dictionaries.

2. Tuples

3. Arrays

## Dictionaries

If we have set of data that are related to each other, we may choose to store that data in a dictionary.
An example is contact list where associate names with phone numbers. Use **Dict()** to create a dictionary.

In [37]:
MyContact = Dict("Ayyappan"=>"9061309937", "Akash"=>"9937477240")

Dict{String, String} with 2 entries:
  "Ayyappan" => "9061309937"
  "Akash"    => "9937477240"

#### We can add another contact to MyContact as follows

In [38]:
MyContact["Sounak"] = "7586940763"

"7586940763"

#### Lets check the updated MyContact now

In [39]:
MyContact

Dict{String, String} with 3 entries:
  "Ayyappan" => "9061309937"
  "Sounak"   => "7586940763"
  "Akash"    => "9937477240"

#### In MyContact each contact is a "key" and the phone number is the "value".

We can get a value (phone number) by using the associated key (contact name)

In [40]:
MyContact["Akash"]

"9937477240"

#### We can also get a contact and simulataneously delete the contact from our contact list

Use **pop!**

In [41]:
pop!(MyContact,"Akash")

"9937477240"

In [42]:
MyContact

Dict{String, String} with 2 entries:
  "Ayyappan" => "9061309937"
  "Sounak"   => "7586940763"

#### Unlike tuples and arrays, dictionaries are not ordered. So, we cannot index into them.

In [43]:
MyContact["Ayyappan"]

"9061309937"

## Tuples

We can create a tuple by enclosing an ordered sequence of elements in **( )**

In [44]:
MyFavouriteSubjects = ("Math","Physics","Mechanics")

("Math", "Physics", "Mechanics")

#### We can index into a tuple

In [45]:
MyFavouriteSubjects[3]

"Mechanics"

#### Since tuples are immutable, we cannot update a tuple

In [46]:
MyFavouriteSubjects[1] = "Chemistry"

LoadError: MethodError: no method matching setindex!(::Tuple{String, String, String}, ::String, ::Int64)

## Arrays

Mutable and ordered. We can use index into them.

Use **[ ]** to create arrays.

In [47]:
MyStudents = ["Shubham","Ved"," Akash","Ayyappan"]

4-element Vector{String}:
 "Shubham"
 "Ved"
 " Akash"
 "Ayyappan"

In [48]:
MyStudents[3]

" Akash"

In [49]:
Ranks = [1,2.0,3,4]

4-element Vector{Float64}:
 1.0
 2.0
 3.0
 4.0

In [50]:
Ranks[1]

1.0

#### Array elements could be of mixture type variables.

In [51]:
MixType = ["Masiur", 80, 20.5, "Math"]

4-element Vector{Any}:
   "Masiur"
 80
 20.5
   "Math"

#### We can edit an array

Add element using **push!** and remove last element of an array by using **pop!**

In [52]:
push!(MixType, 50)

5-element Vector{Any}:
   "Masiur"
 80
 20.5
   "Math"
 50

In [53]:
pop!(MixType)

50

In [54]:
MixType

4-element Vector{Any}:
   "Masiur"
 80
 20.5
   "Math"

#### We can contruct multidimensional arrays 

Example of 2D and 3D arrays are shown using **rand()**

In [55]:
rand(5,4)

5×4 Matrix{Float64}:
 0.155504  0.640918  0.963727  0.132618
 0.62966   0.761255  0.66737   0.800312
 0.295988  0.117301  0.614529  0.661131
 0.652622  0.50681   0.232879  0.875908
 0.730965  0.857693  0.59498   0.972163

In [56]:
rand(6,4,3)

6×4×3 Array{Float64, 3}:
[:, :, 1] =
 0.752047  0.300725  0.0985098  0.436302
 0.395204  0.446698  0.664295   0.849542
 0.874984  0.243485  0.715646   0.972605
 0.2839    0.145185  0.588118   0.510021
 0.884402  0.652895  0.199214   0.960049
 0.245701  0.792769  0.340034   0.341034

[:, :, 2] =
 0.989053   0.456674  0.446484  0.516422
 0.58507    0.866347  0.702419  0.938081
 0.841694   0.313724  0.326873  0.701081
 0.907665   0.221544  0.632783  0.298593
 0.0457083  0.225995  0.215118  0.232303
 0.471141   0.266174  0.686354  0.31238

[:, :, 3] =
 0.211942  0.852611  0.91971   0.297858
 0.660281  0.804743  0.575996  0.685108
 0.559803  0.113208  0.086629  0.272614
 0.659479  0.287011  0.850278  0.892091
 0.87103   0.377639  0.810722  0.534732
 0.280987  0.535998  0.790108  0.0601692

# Loops

Two types:

1. While loops

2. For loops

## While loops 

The sytanx for a while loop is

while    $\,\,$ **condition**

    loop body
    
end

In [12]:
n = 0
while n < 10
    n += 1
    println(n)
end

1
2
3
4
5
6
7
8
9
10


In [15]:
MyStudents = ["Shubham","Ved","Akash","Ayyappan"]
i = 1
while i <= length(MyStudents)
    student = MyStudents[i]
    println("Hi $student, its great to work with you!")
    i += 1
end

Hi Shubham, its great to work with you!
Hi Ved, its great to work with you!
Hi Akash, its great to work with you!
Hi Ayyappan, its great to work with you!


## for loops

The sytanx for a for loop is

for    $\,\,$ **variable** $\,\,$ in  $\,\,$ **loop iterable**

    loop body
    
end

In [16]:
for n in 1:10
   println(n)
end

1
2
3
4
5
6
7
8
9
10


#### Note that **in** can be replaced by an **=** or **∈** 

In [17]:
for n = 1:10
   println(n)
end

1
2
3
4
5
6
7
8
9
10


In [18]:
for n ∈ 1:10
   println(n)
end

1
2
3
4
5
6
7
8
9
10


#### Use of for loops to create addition tables

In [24]:
m,n = 5,2
A = zeros(m,n)

5×2 Matrix{Float64}:
 0.0  0.0
 0.0  0.0
 0.0  0.0
 0.0  0.0
 0.0  0.0

In [26]:
for i in 1:m
  for j in 1:n
    A[i,j] = i+j
  end
end
A

5×2 Matrix{Float64}:
 2.0  3.0
 3.0  4.0
 4.0  5.0
 5.0  6.0
 6.0  7.0

In [27]:
B = zeros(m,n)

5×2 Matrix{Float64}:
 0.0  0.0
 0.0  0.0
 0.0  0.0
 0.0  0.0
 0.0  0.0

In [28]:
for i in 1:m, j in 1:n
    B[i,j] = i+j
end
B

5×2 Matrix{Float64}:
 2.0  3.0
 3.0  4.0
 4.0  5.0
 5.0  6.0
 6.0  7.0

#### The more "Julia" way to create the addition table would have been with an *array comprehension*

In [29]:
C = [i+j for i in 1:m, j in 1:n]

5×2 Matrix{Int64}:
 2  3
 3  4
 4  5
 5  6
 6  7

#### An *array comphesion* embedded in a for loop

In [30]:
for k in 1:10
   D = [i+j for i in 1:k, j in 1:k]
   display(D)
end

1×1 Matrix{Int64}:
 2

2×2 Matrix{Int64}:
 2  3
 3  4

3×3 Matrix{Int64}:
 2  3  4
 3  4  5
 4  5  6

4×4 Matrix{Int64}:
 2  3  4  5
 3  4  5  6
 4  5  6  7
 5  6  7  8

5×5 Matrix{Int64}:
 2  3  4  5   6
 3  4  5  6   7
 4  5  6  7   8
 5  6  7  8   9
 6  7  8  9  10

6×6 Matrix{Int64}:
 2  3  4   5   6   7
 3  4  5   6   7   8
 4  5  6   7   8   9
 5  6  7   8   9  10
 6  7  8   9  10  11
 7  8  9  10  11  12

7×7 Matrix{Int64}:
 2  3   4   5   6   7   8
 3  4   5   6   7   8   9
 4  5   6   7   8   9  10
 5  6   7   8   9  10  11
 6  7   8   9  10  11  12
 7  8   9  10  11  12  13
 8  9  10  11  12  13  14

8×8 Matrix{Int64}:
 2   3   4   5   6   7   8   9
 3   4   5   6   7   8   9  10
 4   5   6   7   8   9  10  11
 5   6   7   8   9  10  11  12
 6   7   8   9  10  11  12  13
 7   8   9  10  11  12  13  14
 8   9  10  11  12  13  14  15
 9  10  11  12  13  14  15  16

9×9 Matrix{Int64}:
  2   3   4   5   6   7   8   9  10
  3   4   5   6   7   8   9  10  11
  4   5   6   7   8   9  10  11  12
  5   6   7   8   9  10  11  12  13
  6   7   8   9  10  11  12  13  14
  7   8   9  10  11  12  13  14  15
  8   9  10  11  12  13  14  15  16
  9  10  11  12  13  14  15  16  17
 10  11  12  13  14  15  16  17  18

10×10 Matrix{Int64}:
  2   3   4   5   6   7   8   9  10  11
  3   4   5   6   7   8   9  10  11  12
  4   5   6   7   8   9  10  11  12  13
  5   6   7   8   9  10  11  12  13  14
  6   7   8   9  10  11  12  13  14  15
  7   8   9  10  11  12  13  14  15  16
  8   9  10  11  12  13  14  15  16  17
  9  10  11  12  13  14  15  16  17  18
 10  11  12  13  14  15  16  17  18  19
 11  12  13  14  15  16  17  18  19  20